/**
 * Custom Web Push handler for Habitly's PWA.
 *
 * Angular's built-in `ngsw-worker.js` (generated by @angular/service-worker)
 * does not implement the W3C `push` / `notificationclick` event listeners,
 * so we ship this tiny script which gets APPENDED to the generated SW
 * after build via `scripts/append-push-worker.mjs`. Keeping this file
 * separate means:
 *
 *  - Angular keeps owning cache + version updates (we don't fight the
 *    framework's lifecycle).
 *  - This file stays self-contained, easy to audit, and easy to swap out
 *    when the backend's payload shape evolves.
 *
 * Apple/iOS notes (Web Push, Safari 16.4+):
 *  - The SW MUST call `showNotification()` for every `push` event or Apple
 *    silently revokes the subscription. We always call it inside
 *    `event.waitUntil()` with a generic fallback title.
 *  - `display: standalone` in `manifest.webmanifest` is required for the
 *    PushManager to be exposed inside the SW. See manifest.webmanifest.
 *
 * Payload contract (must match push-backend/server.js sendWebPush()):
 *   {
 *     "title": string,
 *     "body":  string,
 *     "data": { "screen": "/habit"|"/journal/..."|"/", "habitId"?: string, "source"?: string },
 *     "imageUrl"?: string
 *   }
 *
 * Snooze handling — the SW has three escalating strategies because Workers
 * don't share cookies/headers with the app and may not have the device key
 * to authenticate `POST /api/snooze` directly:
 *   1. If a window client is open, postMessage `{ type: 'SNOOZE_HABIT' }`
 *      and let the page (which has the device key + subscription) do it.
 *   2. Otherwise, open `/habit/:id?snooze=10` so the page can fire the
 *      snooze call on boot.
 *   3. Best-effort same-origin `/api/snooze-relay` POST for setups that
 *      run a Vercel edge function proxy alongside the static PWA.
 */
/// <reference lib="webworker" />
declare const self: ServiceWorkerGlobalScope;

type PushPayload = {
  title?: string;
  body?: string;
  data?: {
    screen?: string;
    habitId?: string | null;
    source?: string;
  };
  // Legacy/flat shape some backends send — we accept both.
  screen?: string;
  habitId?: string | null;
  source?: string;
  imageUrl?: string;
};

self.addEventListener('push', (event: PushEvent) => {
  event.waitUntil((async () => {
    let payload: PushPayload = {};
    try {
      payload = (event.data?.json() as PushPayload) ?? {};
    } catch {
      try {
        const text = event.data?.text();
        if (text) payload = { body: text };
      } catch {
        // Final fallback — Apple revokes the sub if we don't notify, so we
        // still show a generic notification below.
      }
    }

    const title = payload.title ?? 'Habitly';
    const body  = payload.body  ?? 'Time to build your streak.';
    const data  = payload.data  ?? {};
    const habitId = (data.habitId ?? payload.habitId ?? null) as string | null;
    const screen  = (data.screen  ?? payload.screen  ?? '/') as string;
    const source  = (data.source  ?? payload.source  ?? 'push') as string;

    const options: NotificationOptions & { actions?: Array<{ action: string; title: string }>; renotify?: boolean } = {
      body,
      icon:  '/icons/icon-192x192.png',
      badge: '/icons/icon-72x72.png',
      tag:   habitId ? `habit-${habitId}` : (source || 'habitly'),
      renotify: true,
      data: { screen, habitId, source },
    };

    if (habitId) {
      options.actions = [
        { action: 'DONE',   title: 'Done ✓' },
        { action: 'SNOOZE', title: 'Snooze 10 min' },
      ];
    }

    await self.registration.showNotification(title, options);
  })());
});

self.addEventListener('notificationclick', (event: NotificationEvent) => {
  event.notification.close();
  const data = (event.notification.data ?? {}) as {
    screen?: string;
    habitId?: string | null;
    source?: string;
  };
  const habitId = data.habitId ?? null;
  const screen  = data.screen  ?? '/';
  const targetUrl =
    habitId && screen === '/habit'
      ? `/habit/${habitId}`
      : (screen || '/');

  event.waitUntil((async () => {
    const all = await self.clients.matchAll({ type: 'window', includeUncontrolled: true });

    if (event.action === 'DONE' && habitId) {
      const focused = all.find(c => 'focus' in c) as WindowClient | undefined;
      if (focused) {
        focused.postMessage({ type: 'HABIT_DONE_FROM_PUSH', habitId });
        try { await focused.focus(); } catch {}
        return;
      }
      await self.clients.openWindow(`/habit/${habitId}?markDone=1`);
      return;
    }

    if (event.action === 'SNOOZE' && habitId) {
      // Strategy 1: hand off to an open page (it has the device key + sub).
      const focused = all.find(c => 'focus' in c) as WindowClient | undefined;
      if (focused) {
        focused.postMessage({ type: 'SNOOZE_HABIT', habitId, minutes: 10 });
        try { await focused.focus(); } catch {}
        return;
      }
      // Strategy 2: open a deep-link the page handles on boot.
      try {
        await self.clients.openWindow(`/habit/${habitId}?snooze=10`);
      } catch {}
      // Strategy 3: best-effort same-origin relay (no-op if not deployed).
      try {
        await fetch('/api/snooze-relay', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ habitId, minutes: 10 }),
        });
      } catch {}
      return;
    }

    const existing = all.find(c => 'focus' in c) as WindowClient | undefined;
    if (existing) {
      try { await existing.focus(); } catch {}
      existing.postMessage({ type: 'NAVIGATE', url: targetUrl });
      return;
    }
    await self.clients.openWindow(targetUrl);
  })());
});

export {};
