/**
 * Bumps the patch segment of the app version, fetches the current versionCode
 * from EAS, increments it, and writes both values into the Gradle build file
 * that was generated by `expo prebuild`.
 *
 * Run AFTER `expo prebuild` and BEFORE `gradlew assembleRelease / bundleRelease`.
 *
 * Usage:
 *   node scripts/bump-version.js [profile]   (default profile: production)
 */

const { execSync } = require('child_process');
const fs   = require('fs');
const path = require('path');

const GRADLE_PATH   = path.resolve(__dirname, '../android/app/build.gradle');
const APP_JSON_PATH = path.resolve(__dirname, '../app.json');
const PKG_JSON_PATH = path.resolve(__dirname, '../package.json');
const PROFILE = process.argv[2] || 'production';

// ── 1. Bump patch version in app.json + package.json ─────────────────────────

const appJson = JSON.parse(fs.readFileSync(APP_JSON_PATH, 'utf8'));
const currentVersion = appJson.expo.version;

const parts = currentVersion.split('.');
if (parts.length !== 3) {
  console.error(`Unexpected version format in app.json: "${currentVersion}"`);
  process.exit(1);
}
parts[2] = String(parseInt(parts[2], 10) + 1);
const nextVersion = parts.join('.');

appJson.expo.version = nextVersion;
fs.writeFileSync(APP_JSON_PATH, JSON.stringify(appJson, null, 2) + '\n', 'utf8');
console.log(`app.json  version : ${currentVersion} → ${nextVersion}`);

const pkgJson = JSON.parse(fs.readFileSync(PKG_JSON_PATH, 'utf8'));
pkgJson.version = nextVersion;
fs.writeFileSync(PKG_JSON_PATH, JSON.stringify(pkgJson, null, 2) + '\n', 'utf8');
console.log(`package.json      : → ${nextVersion}`);

// ── 2. Fetch + increment versionCode from EAS ────────────────────────────────

console.log(`\nFetching EAS versionCode (profile: ${PROFILE})...`);

let output;
try {
  output = execSync(
    `eas build:version:get --platform android --profile ${PROFILE} --non-interactive`,
    { cwd: path.resolve(__dirname, '..'), encoding: 'utf8', stdio: ['pipe', 'pipe', 'pipe'] },
  );
} catch (err) {
  console.error('Failed to fetch EAS version:', err.stderr || err.message);
  process.exit(1);
}

const match = output.match(/Android versionCode\s*[-–]\s*(\d+)/i);
if (!match) {
  console.error('Could not parse versionCode from EAS output:\n', output);
  process.exit(1);
}

const currentCode = parseInt(match[1], 10);
const nextCode    = currentCode + 1;
console.log(`EAS versionCode   : ${currentCode} → ${nextCode}`);

// ── 3. Write versionCode + versionName into the prebuild Gradle file ─────────

if (!fs.existsSync(GRADLE_PATH)) {
  console.error('android/app/build.gradle not found — run `expo prebuild` first.');
  process.exit(1);
}

let gradle = fs.readFileSync(GRADLE_PATH, 'utf8');
gradle = gradle.replace(/(\bversionCode\s+)\d+/,    `$1${nextCode}`);
gradle = gradle.replace(/(\bversionName\s+")[^"]*"/, `$1${nextVersion}"`);
fs.writeFileSync(GRADLE_PATH, gradle, 'utf8');

console.log(`build.gradle      : versionCode = ${nextCode}, versionName = "${nextVersion}"`);
console.log('\n✓ Version bump complete. Ready for Gradle build.\n');
