/**
 * Injects the local release signing config into the Gradle build file
 * that was generated by `expo prebuild`.
 *
 * Reads credentials from `keystore.properties` at the project root (gitignored).
 * Run AFTER `expo prebuild` and BEFORE `gradlew assembleRelease / bundleRelease`.
 *
 * What it does:
 *  1. Adds a `release` block inside `signingConfigs { }` using the JKS credentials.
 *  2. Replaces `signingConfig signingConfigs.debug` in the release buildType with
 *     `signingConfig signingConfigs.release`.
 */

const fs   = require('fs');
const path = require('path');

const GRADLE_PATH  = path.resolve(__dirname, '../android/app/build.gradle');
const PROPS_PATH   = path.resolve(__dirname, '../keystore.properties');

// ── 1. Load keystore.properties ───────────────────────────────────────────────

if (!fs.existsSync(PROPS_PATH)) {
  console.error('keystore.properties not found. Create it at the project root.');
  process.exit(1);
}

const props = {};
fs.readFileSync(PROPS_PATH, 'utf8')
  .split('\n')
  .forEach(line => {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) return;
    const idx = trimmed.indexOf('=');
    if (idx === -1) return;
    props[trimmed.slice(0, idx).trim()] = trimmed.slice(idx + 1).trim();
  });

const { storeFile, storePassword, keyAlias, keyPassword } = props;
const missing = ['storeFile', 'storePassword', 'keyAlias', 'keyPassword']
  .filter(k => !props[k] || props[k] === 'FILL_IN');

if (missing.length) {
  console.error(`keystore.properties is missing or has placeholder values for: ${missing.join(', ')}`);
  process.exit(1);
}

// ── 2. Patch build.gradle ─────────────────────────────────────────────────────

if (!fs.existsSync(GRADLE_PATH)) {
  console.error('android/app/build.gradle not found — run `expo prebuild` first.');
  process.exit(1);
}

let gradle = fs.readFileSync(GRADLE_PATH, 'utf8');

// Guard: skip if release signing config is already present.
if (gradle.includes('signingConfigs.release')) {
  console.log('✓ Release signing config already present in build.gradle — skipping.');
  process.exit(0);
}

// Step A — Replace the default signingConfigs block (debug only) with one that
// also contains the release config. We match the exact text expo prebuild
// generates so there's no ambiguity about where to insert.
const DEFAULT_SIGNING_BLOCK =
`    signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
    }`;

const NEW_SIGNING_BLOCK =
`    signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
        release {
            storeFile file('${storeFile}')
            storePassword '${storePassword}'
            keyAlias '${keyAlias}'
            keyPassword '${keyPassword}'
        }
    }`;

if (!gradle.includes(DEFAULT_SIGNING_BLOCK)) {
  console.error(
    'Could not find the default signingConfigs block in build.gradle.\n' +
    'The file may have been manually edited or generated differently.\n' +
    'Edit android/app/build.gradle manually to add the release signing config.',
  );
  process.exit(1);
}

gradle = gradle.replace(DEFAULT_SIGNING_BLOCK, NEW_SIGNING_BLOCK);

// Step B — In buildTypes.release, switch from signingConfigs.debug → .release.
//   There are two occurrences of `signingConfig signingConfigs.debug` — one in
//   the debug buildType (keep it), one in the release buildType (change it).
//   We replace only the second occurrence.
const TOKEN = 'signingConfig signingConfigs.debug';
const parts = gradle.split(TOKEN);
if (parts.length >= 3) {
  // parts: [before-first, between-first-and-second, after-second, ...]
  gradle =
    parts[0] +
    TOKEN +
    parts[1] +
    'signingConfig signingConfigs.release' +
    parts.slice(2).join(TOKEN);
} else {
  console.warn('Could not locate release buildType signing line — check build.gradle manually.');
}

fs.writeFileSync(GRADLE_PATH, gradle, 'utf8');
console.log('✓ Release signing config injected into android/app/build.gradle');
console.log(`  storeFile : ${storeFile}`);
console.log(`  keyAlias  : ${keyAlias}`);
