/**
 * Android/iOS long-press app-icon shortcuts using `expo-quick-actions`.
 *
 * The `icon` string is platform-aware:
 *  - iOS  : uses SF Symbols via the `symbol:` prefix (rendered natively, no
 *           asset needed).
 *  - Android: references a key configured in `app.json` under the
 *             `expo-quick-actions` plugin's `androidIcons` map. Each key
 *             points to a foreground PNG (generated by
 *             `scripts/generate-shortcut-icons.mjs`) + background color.
 *             The plugin emits proper Android adaptive icon drawables at
 *             prebuild time, so plain Material icon names like `add_circle`
 *             do NOT work — they fall back to the launcher icon.
 *
 * Called once at app start so the OS knows what shortcuts to expose.
 */
import * as QuickActions from 'expo-quick-actions';
import { router } from 'expo-router';
import { Platform } from 'react-native';

/** Set up the static list of shortcuts. Safe to call multiple times. */
export async function setupQuickActions(): Promise<void> {
  try {
    await QuickActions.setItems([
      {
        id: 'new-habit',
        title: 'Add Habit',
        subtitle: 'Create a new habit',
        icon: Platform.select({ ios: 'symbol:plus.circle.fill', android: 'add' }),
        params: { route: '/new' },
      },
      {
        id: 'today',
        title: 'Today',
        subtitle: "View today's habits",
        icon: Platform.select({ ios: 'symbol:checkmark.circle.fill', android: 'today' }),
        params: { route: '/(tabs)' },
      },
      {
        id: 'insights',
        title: 'Insights',
        subtitle: 'Your habit strength',
        icon: Platform.select({ ios: 'symbol:chart.bar.fill', android: 'insights' }),
        params: { route: '/insights' },
      },
      {
        id: 'journal',
        title: 'Journal',
        subtitle: 'Reflect on your day',
        icon: Platform.select({ ios: 'symbol:book.fill', android: 'journal' }),
        params: { route: '/journal/today' },
      },
    ]);
  } catch {
    // expo-quick-actions silently no-ops on unsupported platforms
  }
}

/**
 * Subscribe to shortcut taps and navigate the user.
 * Returns an unsubscribe function.
 */
export function subscribeQuickActions(): () => void {
  const sub = QuickActions.addListener(action => {
    const route = action?.params?.route as string | undefined;
    if (!route) return;
    if (route === '/journal/today') {
      router.push({ pathname: '/journal/[date]', params: { date: new Date().toISOString().slice(0, 10) } } as never);
      return;
    }
    router.push(route as never);
  });
  return () => sub.remove();
}
